services:
  server:
    build: ./backend
    restart: "unless-stopped"
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src:ro,Z # Mount for hot reload.
    environment:
      - NODE_ENV=development
    command: bun run dev
